module ViewTest where

import View 
import Test.HUnit

testCases :: [Test]
testCases = testMarkerInRow
            ++ testDrawPoints
            ++ testReNormalize
            ++ testAutoDrawPoints

{-- Test whether inserting marker in a grid uses the correct row --}
testMarkerInRow = [
    TestLabel "Y uses row 0 in grid" $ TestCase $ (drawPoint (0,0) ["  ","  "]) @?= ["o ","  "]
   ,TestLabel "Y uses row 1 in grid" $ TestCase $ (drawPoint (1,1) ["  ","  "]) @?= ["  "," o"]
   ,TestLabel "Y dont uses row 12 in grid" $ TestCase $ (drawPoint (1,12) ["  ","  "]) @?= ["  ","  "]
  ]
testDrawPoints = [
    TestLabel "Drawing a set of points in grid" $ TestCase $ (drawOn [(1,1),(3,2),(2,2)] ["    ","    ","    "]) @?= ["    "," o  ","  oo"]
   ,TestLabel "Drawing a set of points in too small grid" $ TestCase $ (drawOn [(1,1),(3,2),(2,2)] ["   ","   "]) @?= ["   "," o "]
  ]

testReNormalize =
  [
    TestLabel "Renomalizes a single point to (0,0)" $ TestCase $ (renormalizePoints [(7,1)]) @?= [(0,0)]
   ,TestLabel "Renomalizes two point so the relative distance stays, but the there is point on x==0 and one on y==0" $ 
     TestList $ 
       [
        TestCase $ (renormalizePoints [(7,1),(8,2)]) @?= [(0,0),(1,1)]
       ,TestCase $ (renormalizePoints [(1,2),(2,1)]) @?= [(0,1),(1,0)]
       ]
  ]

testAutoDrawPoints =
  [
    TestLabel "Drawing a set of points on autogenerated grid" $ TestCase $ (autoDrawPoints [(1,1),(3,2),(2,2)]) @?= ["o  "," oo"]
   ,TestLabel "Drawing a set of points on autogenerated grid" $ TestCase $ (autoDrawPoints [(0,0),(2,1),(1,1)]) @?= ["o  "," oo"]
   ,TestLabel "Drawing a set of points on autogenerated grid" $ TestCase $ (autoDrawPoints [(6,1),(0,3),(1,1)]) @?= [" o    o","       ","o      "]
  ]
